icons = "awesome"
theme = "nord-dark"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
format = "{1m}"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
format = "{percentage} {time}"
interval = 10

[[block]]
block = "focused_window"
max_width = 30
show_marks = "visible"

[[block]]
block = "music"
buttons = ["play", "prev", "next"]
player = "spotify"

[[block]]
block = "net"
format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "time"
format = "%a %d/%m %r"
interval = 1
